### ISSUE TITLE
NoSuchMethod Exception using 0.10.0.0

### ISSUE THREAD

**Issue by lawrencemq** [apakulov/kafka-graphite#7]
I am trying to test using this metric reporter with a Kafka producer.  Running 0.10.0.0.  

Every time the producer starts up, I get this error regardless on if I set "kafka.graphite.metrics.reporter.enabled" to "true", "false", true, or false. 

Has anyone else come across this or know a workaround?

`Caused by: java.lang.NoSuchMethodError: org.apache.kafka.common.metrics.GraphiteReporter$GraphiteConfig.getBoolean(Ljava/lang/String;)Z
    at org.apache.kafka.common.metrics.GraphiteReporter.init(GraphiteReporter.java:76)
    at org.apache.kafka.common.metrics.Metrics.<init>(Metrics.java:129)
    at org.apache.kafka.common.metrics.Metrics.<init>(Metrics.java:111)
    at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:224)`

**Comment by jklukas** [comment]
I have also seen this. I believe there was a breaking change introduced in 0.10.0.0 and it will be necessary to compile this project against that version in order to use it with 0.10.0.0+ clients.

I think that would mean cutting off support for clients pre-0.10.

Perhaps @apakulov would entertain a PR updating the client version and adding docs to make it clear what versions of this package are compatible with which kafka-client versions?

**Comment by mkargar** [comment]
Attached changes to build.gradle file to get this working for 0.10.0.1
[0_10_0_1.diff.txt](https://github.com/apakulov/kafka-graphite/files/787975/0_10_0_1.diff.txt)

**Comment by apakulov** [comment]
@jklukas should be fixed now.
