### ISSUE TITLE
Confluent MetricsReporter support

### ISSUE THREAD

**Issue by epheatt** [apakulov/kafka-graphite#9]
I am able to collect the client metrics for kafka-connect service but for the confluent schema-registry when I enable the client metrics I get the following error

[2017-08-04 00:16:31,871] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain:51)
java.lang.RuntimeException: org.apache.kafka.common.metrics.GraphiteReporter is not an instance of io.confluent.common.metrics.MetricsReporter
	at io.confluent.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:220)
	at io.confluent.rest.Application.<init>(Application.java:97)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.<init>(SchemaRegistryRestApplication.java:47)
	at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:42)

**Comment by apakulov** [comment]
Thanks for reporting this issue @epheatt 
I'll take a look.
